griekseWoordentekst2 = {
    "ἐστί(ν)": "(hij/zij/het/er) is, bestaat",
    "ὁ, ἡ, τό": "de, het",
    "γῆ": "land, aarde",
    "ὁ ποταμός": "rivier",
    "ἡ πέτρα": "rots, rotsblok",
    "τό δένδρον": "boom",
    "ὁ ἄνθρωπος": "mens",
    "ὁ θεός": "god",
    "ἡ μάχη": "strijd, gevecht",
    "τό ἔργον": "werk, taak, daad",
    "πρῶτον": "eerst",
    "ἡ θεά": "godin",
    }

griekseWoordentekst3 = {
    "ὁ βίος": "(het) leven",
    "ἀεί": "altijd, steeds",
    "ὁ ἥλιος": "zon",
    "νοέω": "waarnemen, opmerken",
    "μέν...δέ": "1 (weliswaar) ... maar 2 ... en",
    "τὸ πεδίον": "vlakte",
    "τὸ θηρίον": "(wild) dier",
    "φέρω": "dragen, brengen",
    "κατά, καθ' + acc": "(verspreid) over",
    "ὁ ἵππος": "paard",
    "ἀλλά, ἀλλ'": "maar",
    "δάμαζω": "temmen",
    "ἀγω": "leiden, brengen",
    "λέγω": "zeggen, spreken",
    "ὁ ἐπίτροπος": "opzichter, beheerder",
    "νῦν": "nu, op dit moment",
    "αὐτίκα": "meteen",
    "ὀνομάζω": "noemen"
}

griekseWoordentekst4 = {
    "τὸ τέκνον" : "kind",
    "τίκτω" : "ter wereld brengen, voortbrengen",
    "ἡ κόρη" : "meisje",
    "ὁ θρόνος" : "troon",
    "οὖν" : "dus, dan, nu",
    "οὕτω(ς)" : "zo, op deze manier",
    "τέλος" : "tenslotte",
    "ὁ δόλος" : "list, bedrog",
    "ὁ υἱός" : "zoon",
    "πρός" : "naar (toe), tot, tegen",
    "ὁ ἀδελφός" : "broer",
    "ἡ ἀδελφή" : "zus",
    "ἔχω" : "hebben, houden",
    "εἰς + acc" : "naar (binnen)"
}

griekseWoordentekst6 = {
    "ὁ ἡγεμών, ἡγεμόνος": "leider, aanvoerder",
    "ἡ γυνή, γυναικός": "vrouw",
    "τὸ ὄνομα, ὀνόματος": "naam",
    "ἔγγυς": "dichtbij",
    "ἡ πυρ, πυρος": "vuur",
    "μόνον": "alleen (maar)",
    "ἡ τέχνη": "kunst, vaardigheid",
    "τὰ ὅπλα": "wapens",
    "ὁ δορυ, δόρατος": "lans",
    "ἡ ἀσπίς, ἀσπίδος": "schild",
    "διὰ, δι": "1 door ... heen 2 gedurende",
    "ὁ Ἕλλην, Ἕλληνος": "Griek",
    "βλέπω": "kijken",
    "τὸ πρᾶγμα, πράγματος": "zaak, gebeurtenis",
    "μάλα, μᾶλ'": "zeer, erg",
    "ἐκ, ἐξ + gen": "uit",
    "ἡ μήτηρ, μητρός": "moeder",
    "ὁ πατήρ, πατρός": "vader",
    "ἡ κεφαλή": "hoofd",
    "ἡ ἐσθής, ἐσθῆτος": "kleding(stuk)",
    "ἤδη": "al, reeds (vanaf) nu",
    "ἡ θυγάτηρ, θυγατρός": "dochter"
}

griekseWoordentekst7 = {
    "ὁ ἥρως, ἥρωος": "held",
    "ἀντὶ, ἀντ', ἀνθ' + gen": "in ruil voor, in plaats van",
    "κτείνω": "doden",
    "ὁ φόβος": "angst",
    "φεύγω": "vluchten, ontvluchten",
    "ὁ χῶρος": "gebied, plaats",
    "ἡ ἀρετή": "dapperheid, voortreffelijkheid",
    "φαίνω": "laten zien, tonen",
    "εθελω": "willen",
    "βοηθέω + dat": "helpen",
    "ὁ ἀνήρ, ἀνδρός": "man",
    "ὁ παῖς, παιδός": "kind",
    "παρέχω": "geven, verschaffen",
    "ὡς": "(zo)als",
    "εἰ": "als, indien",
    "ἐν + dat": "in, op, bij",
    "χαίρω": "blij zijn",
    "τὸ δῶρον": "geschenk",
    "ὡς ταχιστα":"1 zo snel mogelijk 2 zodra",
    "ἡ βοήθεια": "hulp"
}

griekseWoordentekst8 = {
    "ἡ Ἑλλάς, Ἑλλάδος": "Griekenland",
    "σύν + dat.": "met",
    "αὐτός, αὐτή, αὐτό": "gen/dat/acc hij, zij, het",
    "ὁ στόλος": "reis, expeditie",
    "ποιέω": "maken, doen",
    "ὁ λιμήν, λιμένος": "haven",
    "τὸ πλοῖον": "vaartuig, schip",
    "θαυμάζω": "bewonderen",
    "ἐγώ / ἐμοῦ / ἐμοί / ἐμέ": "ik, mij",
    "σύ / σοῦ / σοί / σέ": "jij / jou, u",
    "ὦ": "o",
    "ὁ φίλος": "vriend",
    "ὁ κίνδυνος": "gevaar",
    "ἡμᾶς": "wij / ons",
    "ὑμείς/ὑμών/ὑμᾶς": "jullie",
    "ἡ σοφία": "(vak)kennis, wijsheid",
    "ἡ θάλαττα": "zee",
    "ἡ τιμή": "eer, aanzien"
}

griekseWoordentekst9 = {
    "οὐ": "waar",
    "ὁ γέρων, γέροντος": "oude man",
    "τερι + gen": "over, om",
    "ἡ δίκη": "straf",
    "τὸ δεῖπνον": "maaltijd",
    "ἁρπάζω": "roven",
    "παρασκευάζω": "klaarmaken",
    "ἥκω": "komen, gekomen zijn",
    "φεύγω": "achtervolgen, wegjagen",
    "διαφθείρω": "vernietigen, bederven",
    "πέμπω": "zenden, sturen",
    "ὁ λόγος": "woord, verhaal",
    "πάλιν": "opnieuw",
    "ἡ πρύμνα": "achtersteven",
    "ἡ ὁδός": "weg, tocht",
}